query AlbumConnection($limit: Int!, $nextPageCursor: Int) {
    albumConnection(limit: $limit, nextPageCursor: $nextPageCursor) {
        nodes {
            name
            id
        }
        pageInfo {
            limit
            nextPageCursor
        }
    }
}
