query AlbumConnection {
    albumConnection {
        nodes {
            name
            id
        }
        pageInfo {
            limit
            hasNextPage
            hasPrevPage
            prevPageCursor
            nextPageCursor
        }
    }
}
