query ImageConnection($limit: Int, $albumId: Int) {
    imageConnection(limit: $limit, albumId: $albumId) {
        nodes {
            fileName
            location
            id
        }
        pageInfo {
            limit
            hasNextPage
            hasPrevPage
            prevPageCursor
            nextPageCursor
        }
    }
}
