query ImageConnection($limit: Int!, $nextPageCursor: Int, $albumId: Int, $fileName: String, $location: String) {
    imageConnection(limit: $limit, nextPageCursor: $nextPageCursor, albumId: $albumId, fileName: $fileName, location: $location) {
        nodes {
            fileName
            location
            id
            createdAt
        }
        pageInfo {
            limit
            nextPageCursor
        }
    }
}
